import { MenuItem } from "@/types";

/**
 * Mock menu items for the restaurant
 * Includes appetizers, main courses, desserts, and beverages
 */
export const mockMenuItems: MenuItem[] = [
  // APPETIZERS
  {
    id: "menu-1",
    name: "Caesar Salad",
    description: "Fresh romaine lettuce with parmesan cheese, croutons, and Caesar dressing",
    category: "appetizer",
    price: 8.99,
    image: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400",
    isAvailable: true,
    preparationTime: 10,
    ingredients: ["Romaine lettuce", "Parmesan cheese", "Croutons", "Caesar dressing"],
    allergens: ["Dairy", "Gluten"],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "menu-2",
    name: "Bruschetta",
    description: "Grilled bread topped with fresh tomatoes, garlic, basil, and olive oil",
    category: "appetizer",
    price: 7.50,
    image: "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=400",
    isAvailable: true,
    preparationTime: 12,
    ingredients: ["Bread", "Tomatoes", "Garlic", "Basil", "Olive oil"],
    allergens: ["Gluten"],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "menu-3",
    name: "Buffalo Wings",
    description: "Crispy chicken wings tossed in spicy buffalo sauce with ranch dip",
    category: "appetizer",
    price: 11.99,
    image: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=400",
    isAvailable: true,
    preparationTime: 15,
    ingredients: ["Chicken wings", "Buffalo sauce", "Ranch dressing"],
    allergens: ["Dairy"],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "menu-4",
    name: "Mozzarella Sticks",
    description: "Breaded and fried mozzarella cheese served with marinara sauce",
    category: "appetizer",
    price: 9.50,
    image: "https://images.unsplash.com/photo-1531749668029-2db88e4276c7?w=400",
    isAvailable: true,
    preparationTime: 10,
    ingredients: ["Mozzarella cheese", "Breadcrumbs", "Marinara sauce"],
    allergens: ["Dairy", "Gluten"],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },

  // MAIN COURSES
  {
    id: "menu-5",
    name: "Grilled Salmon",
    description: "Fresh Atlantic salmon grilled to perfection with lemon butter sauce and vegetables",
    category: "main_course",
    price: 24.99,
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400",
    isAvailable: true,
    preparationTime: 25,
    ingredients: ["Salmon", "Lemon", "Butter", "Mixed vegetables"],
    allergens: ["Fish", "Dairy"],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "menu-6",
    name: "Ribeye Steak",
    description: "12oz premium ribeye steak with garlic mashed potatoes and seasonal vegetables",
    category: "main_course",
    price: 32.99,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400",
    isAvailable: true,
    preparationTime: 30,
    ingredients: ["Ribeye steak", "Potatoes", "Garlic", "Butter", "Vegetables"],
    allergens: ["Dairy"],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "menu-7",
    name: "Chicken Alfredo Pasta",
    description: "Creamy fettuccine alfredo with grilled chicken breast and parmesan",
    category: "main_course",
    price: 18.99,
    image: "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=400",
    isAvailable: true,
    preparationTime: 20,
    ingredients: ["Fettuccine", "Chicken breast", "Cream", "Parmesan cheese"],
    allergens: ["Gluten", "Dairy"],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "menu-8",
    name: "Vegetarian Pizza",
    description: "Wood-fired pizza with fresh vegetables, mozzarella, and tomato sauce",
    category: "main_course",
    price: 16.50,
    image: "https://images.unsplash.com/photo-1511689660979-10d2b1aada49?w=400",
    isAvailable: true,
    preparationTime: 18,
    ingredients: ["Pizza dough", "Tomato sauce", "Mozzarella", "Bell peppers", "Mushrooms", "Olives"],
    allergens: ["Gluten", "Dairy"],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "menu-9",
    name: "Fish and Chips",
    description: "Beer-battered cod with crispy fries and tartar sauce",
    category: "main_course",
    price: 17.99,
    image: "https://images.unsplash.com/photo-1579208575657-c595a05383b7?w=400",
    isAvailable: true,
    preparationTime: 22,
    ingredients: ["Cod", "Beer batter", "Potatoes", "Tartar sauce"],
    allergens: ["Fish", "Gluten"],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "menu-10",
    name: "Vegan Buddha Bowl",
    description: "Quinoa, roasted vegetables, chickpeas, avocado, and tahini dressing",
    category: "main_course",
    price: 15.99,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400",
    isAvailable: true,
    preparationTime: 18,
    ingredients: ["Quinoa", "Mixed vegetables", "Chickpeas", "Avocado", "Tahini"],
    allergens: ["Sesame"],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },

  // DESSERTS
  {
    id: "menu-11",
    name: "Chocolate Lava Cake",
    description: "Warm chocolate cake with molten center served with vanilla ice cream",
    category: "dessert",
    price: 8.50,
    image: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=400",
    isAvailable: true,
    preparationTime: 15,
    ingredients: ["Chocolate", "Flour", "Eggs", "Butter", "Vanilla ice cream"],
    allergens: ["Gluten", "Dairy", "Eggs"],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "menu-12",
    name: "Tiramisu",
    description: "Classic Italian dessert with coffee-soaked ladyfingers and mascarpone",
    category: "dessert",
    price: 7.99,
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400",
    isAvailable: true,
    preparationTime: 10,
    ingredients: ["Ladyfingers", "Coffee", "Mascarpone cheese", "Cocoa powder"],
    allergens: ["Gluten", "Dairy", "Eggs"],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "menu-13",
    name: "Cheesecake",
    description: "New York style cheesecake with berry compote",
    category: "dessert",
    price: 7.50,
    image: "https://images.unsplash.com/photo-1533134242-9735b609d849?w=400",
    isAvailable: true,
    preparationTime: 8,
    ingredients: ["Cream cheese", "Graham crackers", "Eggs", "Berries"],
    allergens: ["Gluten", "Dairy", "Eggs"],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "menu-14",
    name: "Ice Cream Sundae",
    description: "Three scoops of ice cream with chocolate sauce, whipped cream, and cherry",
    category: "dessert",
    price: 6.99,
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400",
    isAvailable: true,
    preparationTime: 5,
    ingredients: ["Ice cream", "Chocolate sauce", "Whipped cream", "Cherry"],
    allergens: ["Dairy"],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },

  // BEVERAGES
  {
    id: "menu-15",
    name: "Fresh Orange Juice",
    description: "Freshly squeezed orange juice",
    category: "beverage",
    price: 4.50,
    image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400",
    isAvailable: true,
    preparationTime: 5,
    ingredients: ["Fresh oranges"],
    allergens: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "menu-16",
    name: "Cappuccino",
    description: "Espresso with steamed milk and foam",
    category: "beverage",
    price: 4.99,
    image: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400",
    isAvailable: true,
    preparationTime: 5,
    ingredients: ["Espresso", "Milk"],
    allergens: ["Dairy"],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "menu-17",
    name: "Iced Tea",
    description: "Refreshing iced tea with lemon",
    category: "beverage",
    price: 3.50,
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400",
    isAvailable: true,
    preparationTime: 3,
    ingredients: ["Tea", "Lemon", "Ice"],
    allergens: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "menu-18",
    name: "Craft Beer",
    description: "Selection of local craft beers",
    category: "beverage",
    price: 6.50,
    image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?w=400",
    isAvailable: true,
    preparationTime: 2,
    ingredients: ["Beer"],
    allergens: ["Gluten"],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "menu-19",
    name: "Red Wine",
    description: "House red wine by the glass",
    category: "beverage",
    price: 8.00,
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400",
    isAvailable: true,
    preparationTime: 2,
    ingredients: ["Red wine"],
    allergens: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "menu-20",
    name: "Sparkling Water",
    description: "Premium sparkling mineral water",
    category: "beverage",
    price: 3.00,
    image: "https://images.unsplash.com/photo-1523362628745-0c100150b504?w=400",
    isAvailable: true,
    preparationTime: 1,
    ingredients: ["Sparkling water"],
    allergens: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
];

/**
 * Get menu item by ID
 */
export function getMenuItemById(id: string): MenuItem | undefined {
  return mockMenuItems.find((item) => item.id === id);
}

/**
 * Get menu items by category
 */
export function getMenuItemsByCategory(category: MenuItem["category"]): MenuItem[] {
  return mockMenuItems.filter((item) => item.category === category);
}

/**
 * Get available menu items only
 */
export function getAvailableMenuItems(): MenuItem[] {
  return mockMenuItems.filter((item) => item.isAvailable);
}

/**
 * Search menu items by name or description
 */
export function searchMenuItems(query: string): MenuItem[] {
  const lowerQuery = query.toLowerCase();
  return mockMenuItems.filter(
    (item) =>
      item.name.toLowerCase().includes(lowerQuery) ||
      item.description.toLowerCase().includes(lowerQuery)
  );
}
